/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AInput: typeof import('ant-design-vue/es')['Input']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    DashboardHeader: typeof import('./src/components/DashboardHeader.vue')['default']
    DashboardToolbar: typeof import('./src/components/DashboardToolbar.vue')['default']
    DetailDrawer: typeof import('./src/components/DetailDrawer.vue')['default']
    KPICards: typeof import('./src/components/KPICards.vue')['default']
    PayrollTable: typeof import('./src/components/PayrollTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TrendValue: typeof import('./src/components/TrendValue.vue')['default']
  }
}
